apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  projectID: crossplane-work
  credentials:
    source: Secret
    secretRef:
      namespace: default
      name: gcp-secret
      key: creds
